config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  # get '#albums', to: "albums/get_albums"
  resources :styles do
    patch :shift
  end

  resources :favorites

  resources :albums
  # get'execute/left_arrow', to home#update_styles_left
  # get 'styles/', to: 'styles#edit', as: 'edit_styles'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorites.rb
class Favorites < ApplicationRecord
end

app/models/styles.rb
class Styles < ApplicationRecord
end

app/controllers/albums_controller.rb
require 'json'
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  require 'rest-client'
  # GET /albums or /albums.json
  def index
  end  

  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name, :artist_name, :cover_photo_url, :string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def index
        album_id = params["album_id"]
        song_name = params["song_name"]
        @song_name = song_name

        foundFavorite = Favorites.find_by( album_id:album_id, song_name: song_name )
        
        if foundFavorite === nil
            newFavorite = Favorites.create(album_id: album_id, song_name: song_name)
            @fav_style = "fa-solid fa-star selected-star-color"
        else
            foundFavorite.destroy
            @fav_style = "fa-solid fa-star star-color"
        end     
    end    

end     

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    url="https://resque.stg.hakuapp.com/albums.json"
    response = RestClient.get(url)
    allAlbums = JSON.parse(response)

    styles_cont = Styles.all   
    song_index = nil
    songs = nil
    for album in all_albums

      # getting albums style and matching it by corresponding id
      album_style = styles_cont.detect {|style| style.styles_id === album['id']}
      if album_style.style === "album-div album3"

        # if album style is album3 it is the album whose songs are called
        song_index = album_style.styles_id
        response = RestClient.get("https://resque.stg.hakuapp.com/songs.json?album_id=#{album['id']}")
        songs = JSON.parse(response)

        @album_favorites = Favorites.find_by(album_id: album['id'])
        @album_id = album['id']
      end  
      album['style'] = album_style.style
      
    end
    
    for song in songs
      foundFavorite = Favorites.find_by(album_id: song_index, song_name: song["song_name"])

      if foundFavorite === nil
        song['style'] = "star-color"
      else
        song['style'] = "selected-star-color"  
      end
    end    
    @albms = all_albums
    @album_songs = songs
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

    def index
        stylesCont = Styles.all

        direction = params[:direction]

        isLeft = direction === "left"
        limit = nil
        start = nil
        shift_number = nil

        found = Styles.where(styles_id: 1)

        if isLeft
            limit = 'album5'
            start = 'album1'
            shift_number = 1
        else  
            limit = 'album1'
            start = 'album5'
            shift_number = -1
        end            

        stylesCont.each do |style|
            new_style = nil

            # shift all styles left or right based on direction params
            if style.style === "album-div #{limit}"
                new_style = "album-div #{start}" 
                Styles.where(styles_id: style.styles_id).update(style: new_style)
            else
                new_style = 'album-div album' + "#{(Integer(style.style[-1])+shift_number)}"
                Styles.where(styles_id: style.styles_id).update(style: new_style)
            end

            if style.styles_id === 1
                @style1 = new_style
            elsif style.styles_id === 2
                @style2 = new_style
            elsif style.styles_id === 3
                @style3 = new_style
            elsif style.styles_id === 4
                @style4 = new_style
            elsif style.styles_id === 5
                @style5 = new_style
            end

            if new_style === 'album-div album3'
                # album3 is the selected album. The corresponding id is used to get songs for that album.
                @album_id = style.styles_id
                response = RestClient.get("https://resque.stg.hakuapp.com/songs.json?album_id=#{style.styles_id}")
                songs = JSON.parse(response)

                for song in songs
                    foundFavorite = Favorites.find_by(album_id: style.styles_id, song_name: song["song_name"])
                
                    if foundFavorite === nil
                        song['style'] = 'star-color'
                    else
                        song['style'] = 'selected-star-color'  
                    end
                end   

                @album_songs = songs

            end 
        end     

    end    

    def edit
    end    
end    

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Name:</strong>
    <%= album.name %>
  </p>

  <p>
    <strong>Artist name:</strong>
    <%= album.artist_name %>
  </p>

  <p>
    <strong>Cover photo url:</strong>
    <%= album.cover_photo_url %>
  </p>

  <p>
    <strong>String:</strong>
    <%= album.string %>
  </p>

</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :artist_name, style: "display: block" %>
    <%= form.text_field :artist_name %>
  </div>

  <div>
    <%= form.label :cover_photo_url, style: "display: block" %>
    <%= form.text_field :cover_photo_url %>
  </div>

  <div>
    <%= form.label :string, style: "display: block" %>
    <%= form.text_field :string %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
  <% @albums.each do |album| %>
    <%= render album %>
    <p>
      <%= link_to "Show this album", album %>
    </p>
  <% end %>
</div>

<%= link_to "New album", new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

app/views/favorites/index.js.erb
document.getElementById("<%= @song_name %>").className="<%= @fav_style %>"

app/views/home/index.html.erb
<div class="app-div">
    <div  class="albums-div" >
    <%= button_to styles_path, params: {direction:"left"}, class:"arrow-container-left", remote:true, method: :get do %>
        <i class="fa-solid fa-arrow-left left-arrow-icon"></i>  
    <%end%> 
    <% @albms.each do |albm| %>
        <% style= albm["style"] %>
        <div id="<%= albm['id']%>" class="<%= style %>" >      
            <%= image_tag "#{albm['cover_photo_url']}" %>
            <p class="alb-name"><%= albm['name'].upcase %></p>
            <p class="artist-name"><%= albm['artist_name'].upcase %></p>
        </div>
    <% end %>
    <%= button_to styles_path, params: {direction:"right"}, class:"arrow-container-right", remote:true, method: :get do %>
        <i class="fa-solid fa-arrow-right left-arrow-icon"></i>  
    <%end%> 
    </div>
    <div id="song-list" class="music-list-div">
    <% @album_songs.each do |song| %>
        <%p song %>
        <% favorite_style = "fa-solid fa-star " + song["style"] %>
        <div class="song-div">
            <div class="left-song-itms">
                <div class='song-id' ><%= @album_songs.find_index(song)+1 %></div>
                <%= button_to favorites_path, params: {song_name: song['song_name'], album_id: @album_id }, class:"star-container", remote:true, method: :get do %>
                    <i id="<%= song['song_name']%>" class="<%=favorite_style %>"></i> 
                <%end%> 
                <div class= 'song-name'><%= song['song_name'].upcase %></div>
                <% unless song['song_label'].nil? %>
                <% song['song_label'].each do |label| %>
                    <div class="label"><%= label.upcase %></div>
                <%end%>     
                <%end%>     
            </div>
            <div class="song-duration-div"><%= song['song_duration'] %></div>
        </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/e2f626e9f3.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <title>Jukebox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/styles/index.js.erb
//replace song list div to render new songs

$("#song-list").replaceWith(`
<div id="song-list" class="music-list-div">
    <% @album_songs.each do |song| %>
        <% p song %>
        <% favorite_style = "fa-solid fa-star " + song["style"] %>
        <div class="song-div">
            <div class="left-song-itms">
                <div class='song-id' ><%= @album_songs.find_index(song)+1 %></div>
                <%= button_to favorites_path, params: {song_name: song['song_name'], album_id: @album_id }, class:"star-container", remote:true, method: :get do %>
                    <i id="<%= song['song_name']%>" class="<%=favorite_style %>"></i> 
                <%end%> 
                <div class= 'song-name'><%= song['song_name'].upcase %></div>
                <% unless song['song_label'].nil? %>
                <% song['song_label'].each do |label| %>
                    <div class="label"><%= label.upcase %></div>
                <%end%>     
                <%end%>     
            </div>
            <div class="song-duration-div"><%= song['song_duration'] %></div>
        </div>
    <% end %>
</div>`)

//updating album styles by id corresponding to style id
document.getElementById("1").className="<%= @style1 %>"
document.getElementById("2").className="<%= @style2 %>"
document.getElementById("3").className="<%= @style3 %>"
document.getElementById("4").className="<%= @style4 %>"
document.getElementById("5").className="<%= @style5 %>"